export const contentTypes = [
    'application/javascript',
    'application/octet-stream',
    'application/ogg',
    'application/pdf',
    'application/xhtml+xml',
    'application/json',
    'application/xml',
    'application/zip',
    'application/x-www-form-urlencoded',
    'text/css',
    'text/csv',
    'text/html',
    'text/plain',
    'text/xml',
    'multipart/form-data',
];
